### ISSUE TITLE
announcement: Python 2/3 compatibility

### ISSUE THREAD

**Issue by return42** [mozilla-services/mozservices#36]
I just want to announce that I made Python 2 & 3 compliant implementation. You will find it in my 'six' branch at:

  https://github.com/return42/mozservices

I am working on a bunch of forked mozilla-services repositories. They are all assembled as git-submodules at:

  https://github.com/return42/moz-cloud

To follow the Python 3 movement of the whole set, I recommend to checkout `master` branch from `moz-cloud`. Comments are welcome.

**Comment by Natim** [comment]
Hi @return42 

Thank you for starting that, do you mind starting a PR and giving me access to it so that we can iterate on it together?

**Comment by return42** [comment]
Hi @Natim, I'am very sorry for my late reply .. I have not seen your notice, shame on me ... PR is on the way.
