### ISSUE TITLE
umemcache does not support Python 3

### ISSUE THREAD

**Issue by okin** [mozilla-services/mozservices#41]
This is one of the building blocks that is used by [syncserver](https://github.com/mozilla-services/syncserver).
Unfortunately _mozservices_ currently do not support Python 3 because the used library for implementing memcached clients - `umemcache`.

It would be nice to switch to another library that does support Python 3.
To keep backwards compatibility intact one idea could be to make use of `umemcache` under Python 2 and have another implementation for Python 3. This way an update could happen in-place.

**Comment by mathstuf** [comment]
Is this something that is covered by test cases that would make a port easy to verify that it still works?

**Comment by rfk** [comment]
It doesn't look like there's much test coverage in this repo, but there's good test coverage if used in conjunction with the https://github.com/mozilla-services/syncserver repo, which is probably the best way to confirm that it sitll works end-to-end.

I should also point out that we're currently working on a re-write of the [syncstorage server in rust](https://github.com/mozilla-services/syncstorage-rs/), if only to explain why there's not a lot of activity on moving the current servers to python3.

**Comment by mathstuf** [comment]
OK, thanks for the info.
